name: splash
description: This package contains a few InkSplash and InkRipple alternatives for a better UI
version: 1.0.0-nullsafety
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/splash
issue_tracker: https://github.com/ueman/splash/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.24.0-10.2.pre <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter