name: splash
description: This package contains a few InkSplash and InkRipple alternatives for a better UI
version: 1.0.0
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/splash
issue_tracker: https://github.com/ueman/splash/issues

environment:
  sdk: '>=2.12.0-259.9.beta < 3.0.0'
  flutter: '>=1.26.0-17.6.pre'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter