name: referrer
description: "A Flutter plugin to read various referrer information for incoming deeplinks"
version: 0.0.2
homepage: https://uekoetter.dev
repository: https://github.com/ueman/flutter_referrer_info
issue_tracker: https://github.com/ueman/flutter_referrer_info/issues

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: info.referrer.referrer
        pluginClass: ReferrerPlugin
      ios:
        pluginClass: ReferrerPlugin