name: referrer
description: "A Flutter plugin to read various referrer information for incoming deeplinks"
version: 1.1.0
repository: https://github.com/ueman/dart-packages
issue_tracker: https://github.com/ueman/dart-packages/issues

topics:
 - referrer
 - analytics
 - deeplinks
 - app-links
 - universal-links
 - web-to-app

funding:
  - https://github.com/sponsors/ueman

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: info.referrer.referrer
        pluginClass: ReferrerPlugin
      ios:
        pluginClass: ReferrerPlugin