name: http_image_provider
description: An image provider which makes use of package:http to instead of dart:io
version: 0.0.2
repository: https://github.com/ueman/image_provider/http_image_provider
issue_tracker: https://github.com/ueman/image_provider/issues

topics: 
  - cupertino_http
  - cronet_http
  - image_provider

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  http: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
