name: sentry_plus
description: This package includes a collection of community maintained integrations for Sentry.
version: 0.0.4
repository: https://github.com/ueman/sentry-dart-tools
issue_tracker: https://github.com/ueman/sentry-dart-tools/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  sentry: ^6.4.0
  stack_trace: ^1.10.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  path: ^1.8.0
