name: sentry_plus
description: A collection of community maintained Sentry integrations.
version: 1.0.0

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  sentry: ^6.5.0-beta.2

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  path: ^1.8.0
