name: sentry_flutter_plus
description: This package includes a collection of community maintained integrations for Sentry.
version: 0.0.2
repository: https://github.com/ueman/sentry-dart-tools

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^6.5.1
  sentry_plus: ^0.0.3
  device_info_plus: ^3.2.3
  battery_plus: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter: