name: splash
description: This package contains a few InkSplash and InkRipple alternatives for a better UI
version: 1.2.0
repository: https://github.com/ueman/dart-packages
issue_tracker: https://github.com/ueman/dart-packages/issues

environment:
  sdk: ^3.0.0
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter